apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploys
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: yomipounds/yomikube
        ports:
        - containerPort: 8080
